### ISSUE TITLE
403 HTTP status code

### ISSUE THREAD

**Issue by HannaHUp** [civitai/civitai-python#7]
I got "   raise HTTPException(response.status_code, f"Request failed with status code: {response.status_code}")" when running your example """
input = {
    "model": "urn:air:sd1:checkpoint:civitai:4384@128713",
    "params": {
        "prompt": "RAW photo, face portrait photo of woman, wearing black dress, happy face, hard shadows, cinematic shot, dramatic lighting",
        "negativePrompt": "(deformed, distorted, disfigured:1.3)",
        "scheduler": "EulerA",
        "steps": 20,
        "cfgScale": 7,
        "width": 512,
        "height": 512,
        "clipSkip": 2
    }
}
response = civitai.image.create(input)
"""
I just created the API key.
what could be the reason? what should I do?
Thank you

**Comment by andre-c-andersen** [comment]
I got the same issue, and if I inspect the response it says `{"error":"Insufficient Buzz"}`.

Presumably buying some "Buzz" will help. I will try and see if it helps.

**edit**: Yes, adding "Buzz" did in fact work. I am now getting status code `202`.

**Comment by parth-shah-simform** [comment]
I have 100 buzz in my account but i am still getting the following error. Any idea how to resolve it? I have attached my code and error below.

Code:
```
import civitai

input = {
    "model": "urn:air:sdxl:checkpoint:civitai:372465@914390",
    "params": {
        "prompt": "RAW photo, face portrait photo of 26 y.o woman, wearing black dress, happy face, hard shadows, cinematic shot, dramatic lighting",
        "negativePrompt": "(deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers:1.4), (deformed, distorted, disfigured:1.3)",
        "scheduler": "EulerA",
        "steps": 20,
        "cfgScale": 7,
        "width": 512,
        "height": 512,
        "clipSkip": 2
    }
}

response = civitai.image.create(input)

```


Error I am getting:

```
Traceback (most recent call last):
  File "/home/john/Documents/testing_arena/civitai-api/api.py", line 17, in <module>
    response = civitai.image.create(input)
  File "/home/john/Documents/testing_arena/civitai-api/.venv/lib/python3.10/site-packages/civitai/__init__.py", line 78, in create
    return asyncio.run(async_create())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/john/Documents/testing_arena/civitai-api/.venv/lib/python3.10/site-packages/civitai/__init__.py", line 53, in async_create
    response = await post_v1consumerjobs(job_input, wait=False, api_config_override=self.civitai)
  File "/home/john/Documents/testing_arena/civitai-api/.venv/lib/python3.10/site-packages/civitai/services/async_Jobs_service.py", line 73, in post_v1consumerjobs
    raise HTTPException(response.status_code, f"Request failed with status code: {response.status_code}")
civitai.api_config.HTTPException: 403 Request failed with status code: 403
```

Buzz in my account:

<img width="269" height="93" alt="Image" src="https://github.com/user-attachments/assets/48d70dbf-e45f-4fbe-8dc5-9603dc5020d3" />

**Comment by koenbeuk** [comment]
This client has been retired and is no longer maintained, so this won't be addressed. There is no direct replacement package — please use the Civitai API directly instead: https://developer.civitai.com/orchestration/ (see the README for details, including how to generate a typed client from the OpenAPI spec).
